dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - g++-7
      - libboost1.67-all-dev
      - cmake

script:
  - CXX=/usr/bin/g++-7 CC=/usr/bin/gcc-7 cmake .
  - cmake --build . -- -j2
  - ctest -VV

